export enum LegalEntity {
  INVERSIONES_AVIOA_SAS = 'INVERSIONES AVIOA SAS',
  GESTION_TURISMO_SAS = 'GESTIÓN TURISMO SAS',
  AVIOA_MAYORISTA_SAS = 'AVIOA MAYORISTA SAS',
  HOTELES_DE_LA_MONTANA = 'HOTELES DE LA MONTAÑA',
}
