export enum Office {
  BOGOTA = 'BOGOTA',
  GUARNE = 'GUARNE',
  NUEVA_AVENIDA = 'NUEVA AVENIDA',
  EL_PENOL = 'EL PEÑOL',
  MARINILLA_PARQUE = 'MARINILLA PARQUE',
  MARINILLA_INDUSTRIAL = 'MARINILLA INDUSTRIAL',
  MEDELLIN = 'MEDELLIN',
  SAN_ANTONIO = 'SAN ANTONIO',
  SANTUARIO_PARQUE = 'SANTUARIO PARQUE',
  SANTUARIO_CALLE_DEL_COMERCIO = 'SANTUARIO CALLE DEL COMERCIO',
  TELETRABAJO = 'TELETRABAJO',
}
