FROM node:20-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache netcat-openbsd

# Copiar archivos de dependencias primero
COPY package*.json ./
COPY prisma ./prisma/   

RUN npm install
RUN npm install -g @nestjs/cli

# Copiar el resto del código
COPY . .

# Preparar entrypoint
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.sh && \
    chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

EXPOSE 3000

CMD ["npm", "run", "start:dev"]