FROM node:20-alpine AS builder
WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/

# instala TODO (incluyendo dev)
RUN npm ci

COPY . .

ENV NODE_ENV=production
ENV SKIP_ENV_VALIDATION=true

# Generar prisma
RUN npx prisma generate

# sí existe nest
RUN npm run build

# ----------------------

FROM node:20-alpine AS production
WORKDIR /usr/src/app

RUN addgroup -g 1001 -S nodejs && adduser -S nestjs -u 1001

COPY --from=builder --chown=nestjs:nodejs /usr/src/app/dist ./dist
COPY --from=builder --chown=nestjs:nodejs /usr/src/app/node_modules ./node_modules
COPY --from=builder --chown=nestjs:nodejs /usr/src/app/prisma ./prisma
COPY --chown=nestjs:nodejs package*.json ./
COPY --chown=nestjs:nodejs entrypoint.prod.sh ./

# se elimina devDependencies en producción
RUN npm prune --omit=dev

USER nestjs

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/v1/health || exit 1

# CMD ["node", "dist/src/main.js"]
CMD ["/bin/sh", "./entrypoint.prod.sh"]